(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens={home:$('#home'),ball:$('#ball'),jump:$('#jump')};let current='home';
function stopAll(){stopBall();stopJump()}
function show(name){stopAll();Object.values(screens).forEach(x=>x.classList.remove('active'));screens[name].classList.add('active');current=name;if(name==='ball')startBall();if(name==='jump')startJump()}
$$('[data-game]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.game)));$$('.back').forEach(b=>b.addEventListener('click',()=>show('home')));
function toast(el,text){el.textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),430)}
function lives(el,n){el.textContent='♥'.repeat(n)+'♡'.repeat(3-n)}
function tone(freq=440,d=.05,type='sine'){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;window._ac=window._ac||new A();const a=window._ac,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}catch{}}
function setupCanvas(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1),W=Math.max(1,Math.round(r.width*d)),H=Math.max(1,Math.round(r.height*d));if(canvas.width!==W||canvas.height!==H){canvas.width=W;canvas.height=H}const ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx,w:r.width,h:r.height}}
function rounded(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
function tap(el,fn){if(window.PointerEvent)el.addEventListener('pointerdown',e=>{e.preventDefault();fn(e)},{passive:false});else el.addEventListener('touchstart',e=>{e.preventDefault();fn(e)},{passive:false})}
function drawMichelle(ctx,x,y,s,pose='sit',rot=0,flip=false){ctx.save();ctx.translate(x+s/2,y+s/2);ctx.rotate(rot);ctx.scale(flip?-1:1,1);ctx.translate(-s/2,-s/2);const u=s/100;ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='#583a25';ctx.lineWidth=1.8*u;
  ctx.strokeStyle='#70482a';ctx.lineWidth=10*u;ctx.beginPath();ctx.moveTo(76*u,78*u);ctx.bezierCurveTo(103*u,72*u,106*u,91*u,85*u,95*u);ctx.stroke();ctx.strokeStyle='#3f2a1d';ctx.lineWidth=3*u;ctx.beginPath();ctx.moveTo(94*u,80*u);ctx.lineTo(100*u,85*u);ctx.moveTo(88*u,89*u);ctx.lineTo(96*u,93*u);ctx.stroke();
  ctx.fillStyle='#aa7443';ctx.strokeStyle='#583a25';ctx.lineWidth=1.8*u;ctx.beginPath();ctx.ellipse(51*u,66*u,27*u,30*u,0,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.fillStyle='#fff8ee';ctx.beginPath();ctx.ellipse(51*u,69*u,16*u,22*u,0,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#aa7443';ctx.beginPath();ctx.moveTo(30*u,30*u);ctx.lineTo(25*u,8*u);ctx.lineTo(42*u,24*u);ctx.moveTo(70*u,30*u);ctx.lineTo(76*u,8*u);ctx.lineTo(59*u,24*u);ctx.fill();ctx.stroke();
  ctx.beginPath();ctx.ellipse(51*u,34*u,27*u,24*u,0,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.fillStyle='#efb5ab';ctx.beginPath();ctx.moveTo(29*u,21*u);ctx.lineTo(27*u,12*u);ctx.lineTo(37*u,22*u);ctx.moveTo(72*u,21*u);ctx.lineTo(75*u,12*u);ctx.lineTo(65*u,22*u);ctx.fill();
  ctx.strokeStyle='#4e3423';ctx.lineWidth=3*u;[[46,12,49,23],[56,12,53,23],[37,15,43,24],[65,15,59,24],[28,33,39,36],[74,33,63,36],[27,41,39,41],[75,41,63,41],[31,61,41,64],[70,61,60,64],[30,69,40,72],[71,69,61,72]].forEach(a=>{ctx.beginPath();ctx.moveTo(a[0]*u,a[1]*u);ctx.lineTo(a[2]*u,a[3]*u);ctx.stroke()});
  ctx.fillStyle='#fff8ee';ctx.beginPath();ctx.ellipse(51*u,45*u,15*u,10*u,0,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#c6d86b';ctx.strokeStyle='#493522';ctx.lineWidth=1.5*u;ctx.beginPath();ctx.ellipse(40*u,34*u,6*u,8*u,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.ellipse(62*u,34*u,6*u,8*u,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#172118';ctx.beginPath();ctx.ellipse(40*u,35*u,2.2*u,5*u,0,0,Math.PI*2);ctx.ellipse(62*u,35*u,2.2*u,5*u,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(38.5*u,32*u,1.4*u,0,Math.PI*2);ctx.arc(60.5*u,32*u,1.4*u,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#f09da1';ctx.strokeStyle='#744b46';ctx.lineWidth=u;ctx.beginPath();ctx.moveTo(47*u,44*u);ctx.quadraticCurveTo(51*u,40*u,55*u,44*u);ctx.quadraticCurveTo(51*u,49*u,47*u,44*u);ctx.fill();ctx.stroke();ctx.strokeStyle='#674436';ctx.beginPath();ctx.moveTo(51*u,47*u);ctx.lineTo(51*u,51*u);ctx.moveTo(51*u,51*u);ctx.quadraticCurveTo(47*u,54*u,44*u,52*u);ctx.moveTo(51*u,51*u);ctx.quadraticCurveTo(55*u,54*u,58*u,52*u);ctx.stroke();
  ctx.fillStyle='#fff8ee';ctx.strokeStyle='#583a25';ctx.lineWidth=1.5*u;if(pose==='paw'){ctx.beginPath();ctx.roundRect(12*u,55*u,34*u,11*u,5*u);ctx.fill();ctx.stroke();ctx.fillStyle='#efb0ad';ctx.beginPath();ctx.arc(16*u,60*u,2.6*u,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.roundRect(29*u,77*u,16*u,18*u,7*u);ctx.roundRect(57*u,77*u,16*u,18*u,7*u);ctx.fill();ctx.stroke()}
  if(pose==='jump'){ctx.strokeStyle='#583a25';ctx.lineWidth=1.5*u;ctx.fillStyle='#fff8ee';ctx.beginPath();ctx.roundRect(69*u,65*u,22*u,9*u,4*u);ctx.fill();ctx.stroke()}
  ctx.restore()}

const bc=$('#ballCanvas'),bs=$('#ballScore'),bl=$('#ballLives'),bt=$('#ballToast'),bo=$('#ballOver');let bRun=false,bRAF=0,bx=0,by=0,bvx=0,bvy=0,bScore=0,bLives=3,bLast=0,bSlapUntil=0;
function resetBall(){const{w,h}=setupCanvas(bc);bx=w*.25+Math.random()*w*.5;by=h*.24;bvx=(Math.random()<.5?-1:1)*175;bvy=-180}
function startBall(){bo.classList.remove('show');bScore=0;bLives=3;bs.textContent='0';lives(bl,3);resetBall();bRun=true;bLast=performance.now();bRAF=requestAnimationFrame(ballLoop)}function stopBall(){bRun=false;cancelAnimationFrame(bRAF)}
function ballLoop(now){if(!bRun)return;const{ctx,w,h}=setupCanvas(bc),dt=Math.min(.028,(now-bLast)/1000||.016);bLast=now;bvy+=520*dt;bx+=bvx*dt;by+=bvy*dt;const r=22;if(bx<r){bx=r;bvx=Math.abs(bvx)}if(bx>w-r){bx=w-r;bvx=-Math.abs(bvx)}if(by<82+r){by=82+r;bvy=Math.abs(bvy)*.8}if(by>h-r-4){bLives--;lives(bl,bLives);toast(bt,'MISS');tone(120,.08,'square');if(bLives<=0){endBall();return}bx=w*.25+Math.random()*w*.5;by=h*.25;bvy=-230;bvx=(Math.random()<.5?-1:1)*(175+bScore*7)}
 const floor=h*.72,g=ctx.createLinearGradient(0,0,0,floor);g.addColorStop(0,'#dff4ff');g.addColorStop(1,'#f9fcff');ctx.fillStyle=g;ctx.fillRect(0,0,w,floor);ctx.fillStyle='#ead0a5';ctx.fillRect(0,floor,w,h-floor);ctx.fillStyle='#d0ab76';ctx.fillRect(0,floor,w,5);ctx.globalAlpha=.13;ctx.fillStyle='#36556a';ctx.beginPath();ctx.ellipse(w*.5,h*.89,85,15,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;const s=Math.min(210,w*.45),x=w*.5-s/2,y=h-s*.86;drawMichelle(ctx,x,y,s,now<bSlapUntil?'paw':'sit',now<bSlapUntil?-.05:0);ctx.strokeStyle='rgba(24,132,205,.22)';ctx.lineWidth=2;ctx.setLineDash([6,8]);ctx.beginPath();ctx.ellipse(w*.5,h*.74,96,67,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);const bg=ctx.createRadialGradient(bx-7,by-8,3,bx,by,r);bg.addColorStop(0,'#d5f3ff');bg.addColorStop(.27,'#55c1ff');bg.addColorStop(1,'#0876c8');ctx.fillStyle=bg;ctx.beginPath();ctx.arc(bx,by,r,0,Math.PI*2);ctx.fill();bRAF=requestAnimationFrame(ballLoop)}
function slap(){if(!bRun)return;const r=bc.getBoundingClientRect(),dx=bx-r.width*.5,dy=by-r.height*.74,dist=Math.hypot(dx,dy);bSlapUntil=performance.now()+160;if(dist<125&&by>r.height*.57){bScore++;bs.textContent=bScore;bvy=-(320+Math.min(170,bScore*9));bvx=(dx===0?(Math.random()<.5?-1:1):Math.sign(dx))*(185+Math.min(220,bScore*12));toast(bt,bScore%5===0?'NICE!':'HIT!');tone(640+Math.min(420,bScore*18),.045,'triangle')}else{toast(bt,'SWISH');tone(240,.035,'square')}}function endBall(){bRun=false;cancelAnimationFrame(bRAF);const best=Math.max(bScore,+(localStorage.michelleBallBest||0));localStorage.michelleBallBest=best;$('#ballSummary').textContent=`Score ${bScore} · Best ${best}`;bo.classList.add('show')}tap(bc,slap);$('#ballRetry').addEventListener('click',startBall);

const jc=$('#jumpCanvas'),js=$('#jumpScore'),jl=$('#jumpLives'),jt=$('#jumpToast'),jo=$('#jumpOver');let jRun=false,jRAF=0,jScore=0,jLives=3,jRound=1,jJump=false,jStart=0,jHand='idle',jHandT=0,jNext=0,jLast=0,jHit=false;
function startJump(){jo.classList.remove('show');jScore=0;jLives=3;jRound=1;js.textContent='0';lives(jl,3);$('#roundLabel').textContent='ROUND 1';setupCanvas(jc);jRun=true;jLast=performance.now();scheduleHand(jLast);jRAF=requestAnimationFrame(jumpLoop)}function stopJump(){jRun=false;cancelAnimationFrame(jRAF)}function scheduleHand(now){jHand='idle';jNext=now+Math.max(650,1450-jRound*60)+Math.random()*Math.max(380,760-jRound*20);jHit=false}
function handGeom(w,h,now){let y=-h*.25,rot=0;if(jHand==='warn'){const t=(now-jHandT)/500;y=-h*.18+Math.sin(t*19)*4;rot=Math.sin(t*20)*.04}else if(jHand==='hit'){const t=Math.min(1,(now-jHandT)/390),s=t<.52?t/.52:(1-t)/.48;y=-h*.16+s*h*.56;rot=-.08*s}return{x:w*.38,y,wid:w*.28,hei:h*.30,rot}}
function drawHand(ctx,g){ctx.save();ctx.translate(g.x+g.wid/2,g.y);ctx.rotate(g.rot);ctx.fillStyle='#ffc39b';ctx.strokeStyle='#d58f6b';ctx.lineWidth=2.4;ctx.beginPath();ctx.roundRect(-g.wid*.22,g.hei*.30,g.wid*.54,g.hei*.46,g.wid*.17);ctx.fill();ctx.stroke();for(let i=0;i<4;i++){ctx.beginPath();ctx.roundRect(-g.wid*.27+i*g.wid*.145,g.hei*(.02+i*.01),g.wid*.14,g.hei*(.42-i*.025),g.wid*.07);ctx.fill();ctx.stroke()}ctx.beginPath();ctx.roundRect(-g.wid*.37,g.hei*.37,g.wid*.19,g.hei*.33,g.wid*.09);ctx.fill();ctx.stroke();ctx.restore()}
function catGeom(w,h,now){const floor=h*.78,table=h*.49,s=Math.min(190,w*.40);if(!jJump)return{x:w*.06,y:floor-s*.64,s,p:0,rot:0};const dur=Math.max(690,940-jRound*11),p=Math.min(1,(now-jStart)/dur),x=w*.06+w*.62*p,base=floor-s*.64+(table-floor+s*.08)*p,arc=Math.sin(Math.PI*p)*h*.28;return{x,y:base-arc,s,p,rot:-.12+.26*p}}
function overlap(a,b,p=0){return !(a.x+a.w-p<b.x+p||a.x+p>b.x+b.w-p||a.y+a.h-p<b.y+p||a.y+p>b.y+b.h-p)}
function jumpLoop(now){if(!jRun)return;const{ctx,w,h}=setupCanvas(jc);jLast=now;if(jHand==='idle'&&now>=jNext){jHand='warn';jHandT=now;tone(330,.05,'square')}else if(jHand==='warn'&&now-jHandT>=Math.max(250,560-jRound*17)){jHand='hit';jHandT=now;tone(120,.08,'sawtooth')}else if(jHand==='hit'&&now-jHandT>=420){scheduleHand(now)}
 const floor=h*.78,g=ctx.createLinearGradient(0,0,0,floor);g.addColorStop(0,'#fff3e5');g.addColorStop(1,'#f8e8d3');ctx.fillStyle=g;ctx.fillRect(0,0,w,floor);ctx.fillStyle='#dfc39d';ctx.fillRect(0,floor,w,h-floor);ctx.fillStyle='#caa06a';ctx.fillRect(0,floor,w,5);const tx=w*.58,ty=h*.48,tw=w*.43;rounded(ctx,tx,ty,tw,18,9,'#8d5b38');ctx.fillStyle='#71462b';ctx.fillRect(tx+tw*.12,ty+18,16,h*.33);ctx.fillRect(tx+tw*.82,ty+18,16,h*.33);const lw=tw*.62,lh=lw*.55,lx=tx+tw*.22,ly=ty-lh+3;rounded(ctx,lx,ly,lw,lh,6,'#aeb4b9');rounded(ctx,lx+5,ly+5,lw-10,lh-11,3,'#1b2329');rounded(ctx,lx-10,ty-2,lw+20,9,4,'#9ba2a8');ctx.fillStyle='#778089';ctx.font='700 10px -apple-system';ctx.textAlign='center';ctx.fillText('NOTEBOOK',lx+lw/2,ly+lh*.56);if(jHand==='warn'){ctx.save();ctx.globalAlpha=.20+.25*Math.abs(Math.sin(now/90));ctx.fillStyle='#ff4355';ctx.beginPath();ctx.ellipse(w*.50,h*.39,w*.18,h*.22,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.font=`900 ${Math.min(48,w*.11)}px system-ui`;ctx.fillStyle='#ef9b13';ctx.fillText('⚠️',w*.51,h*.28)}const hg=handGeom(w,h,now);drawHand(ctx,hg);const cg=catGeom(w,h,now);drawMichelle(ctx,cg.x,cg.y,cg.s,jJump?'jump':'sit',cg.rot);if(jJump&&jHand==='hit'&&!jHit){const a={x:cg.x+cg.s*.18,y:cg.y+cg.s*.16,w:cg.s*.64,h:cg.s*.68},b={x:hg.x+hg.wid*.09,y:hg.y+hg.hei*.15,w:hg.wid*.82,h:hg.hei*.68};if(overlap(a,b,8)){jHit=true;jJump=false;jLives--;lives(jl,jLives);toast(jt,'BONK!');tone(105,.13,'square');if(jLives<=0){endJump();return}else scheduleHand(now+350)}}if(jJump&&cg.p>=1&&!jHit){jJump=false;jScore++;jRound++;js.textContent=jScore;$('#roundLabel').textContent='ROUND '+jRound;toast(jt,'SAFE!');tone(760,.06,'triangle');scheduleHand(now+320)}jRAF=requestAnimationFrame(jumpLoop)}
function doJump(){if(!jRun||jJump)return;jJump=true;jHit=false;jStart=performance.now();tone(480,.035,'triangle')}function endJump(){jRun=false;cancelAnimationFrame(jRAF);const best=Math.max(jScore,+(localStorage.michelleJumpBest||0));localStorage.michelleJumpBest=best;$('#jumpSummary').textContent=`Safe ${jScore} · Best ${best}`;jo.classList.add('show')}tap(jc,doJump);$('#jumpRetry').addEventListener('click',startJump);
window.addEventListener('resize',()=>{if(current==='ball')setupCanvas(bc);if(current==='jump')setupCanvas(jc)});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAll()});
})();
